name: check
on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - id: cache-typstyle
        uses: actions/cache@v4
        with:
          path: typstyle
          key: ${{ runner.os }}-typstyle-0.13.9
      - if: steps.cache-typstyle.outputs.cache-hit != 'true'
        run: |
          curl -L -o typstyle https://github.com/Enter-tainer/typstyle/releases/download/v0.13.9/typstyle-x86_64-unknown-linux-gnu && \
          chmod +x typstyle
      - run: ./typstyle --check .
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: typst-community/setup-typst@v4
        with:
          typst-version: ^0.13.0
      - run: ./x build
