name: build-then-deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: typst-community/setup-typst@v4
        with:
          typst-version: ^0.13.0
      # Fonts not installed with typst
      - id: cache-fonts
        uses: actions/cache@v4
        with:
          path: fonts
          key: ${{ runner.os }}-fonts-1
      - if: steps.cache-fonts.outputs.cache-hit != 'true'
        run: |
          curl -L -o latin-modern.zip \
            'https://www.gust.org.pl/projects/e-foundry/latin-modern/download/lm2.004otf.zip' && \
          unzip latin-modern.zip -d fonts && \
          curl -L -o Bareonbatang.zip \
            --referer 'https://copyright.keris.or.kr/wft/fntDwnldView' \
            -d 'fntGrpId=GFT202301120000000000002&fntFileId=FTF202312080000000000070' \
            'https://copyright.keris.or.kr/cmm/fntDwnldById' && \
          unzip Bareonbatang.zip '*.otf' -d fonts
      - run: ./x build
        env:
          TYPST_FONT_PATHS: ./fonts
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - id: deployment
        uses: actions/deploy-pages@v4
