name: build-then-deploy
on: [push, pull_request]

jobs:
  deploy:
    # Only in main branch
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: typst-community/setup-typst@v4
        with:
          typst-version: ^0.13.0
      # Latin Modern Sans is not installed with typst
      - id: cache-fonts
        uses: actions/cache@v4
        with:
          path: fonts
          key: ${{ runner.os }}-fonts
      - if: steps.cache-fonts.outputs.cache-hit != 'true'
        run: |
          curl -L -o latin-modern.zip https://www.gust.org.pl/projects/e-foundry/latin-modern/download/lm2.004otf.zip && \
          unzip latin-modern.zip -d fonts && \
          curl -L -o Pretendard.zip https://github.com/orioncactus/pretendard/releases/download/v1.3.9/Pretendard-1.3.9.zip && \
          unzip -j Pretendard.zip "public/static/*.otf" -d fonts
      - run: ./x build
        env:
          TYPST_FONT_PATHS: ./fonts
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - id: deployment
        uses: actions/deploy-pages@v4
  build:
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: typst-community/setup-typst@v4
        with:
          typst-version: ^0.13.0
      - run: ./x build
